---
title: "Filtering_mutations"
author: "Shuo Wang"
date: "2024-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Import mutation data
```{r import data}
library(readxl)
p33b <- read_excel("/Users/shuo/Desktop/Project2_Discovering neoantigen specificity of tumor reactive T cells/GlioblastomaCollaboration/Data/Mutations/Pt33/B33.GATK.snp.annovar.hg38_multianno.xlsx")
p33tf <- read_excel("/Users/shuo/Desktop/Project2_Discovering neoantigen specificity of tumor reactive T cells/GlioblastomaCollaboration/Data/Mutations/Pt33/T33F.GATK.snp.annovar.hg38_multianno.xlsx")
p33tr <- read_excel("/Users/shuo/Desktop/Project2_Discovering neoantigen specificity of tumor reactive T cells/GlioblastomaCollaboration/Data/Mutations/Pt33/T33R.GATK.snp.annovar.hg38_multianno.xlsx")
```

#Filter mutations
Filter for exonic nonsynonymous variants
Filter out polymorphisms from dbSNP (build 150)
```{r filter mutations}
library(dplyr)
mut_p33b <- p33b %>% filter(ID == ".") %>% filter(Func %in% c("exonic")) %>%
  filter(ExonicFunc != "synonymous SNV")

mut_p33tf <- p33tf %>% filter(ID == ".") %>% filter(Func %in% c("exonic")) %>%
  filter(ExonicFunc != "synonymous SNV")

mut_p33tr <- p33tr %>% filter(ID == ".") %>% filter(Func %in% c("exonic")) %>%
  filter(ExonicFunc != "synonymous SNV")
```

#Substract mutations from PBMC
```{r add sample index}
mut_p33b$sample <- "PBMC"
mut_p33tf$sample <- "tumor"
mut_p33tr$sample <- "tumor"
```

```{r remove different colnames}
mut_p33b$B33 <- NULL
mut_p33tf$T33F <- NULL
mut_p33tr$T33R <- NULL
```

```{r remove duplicates}
mut_p33tf <- as.data.frame(rbind(mut_p33b, mut_p33tf))
sum(duplicated(mut_p33tf$AAChange))
mut_p33tf <- mut_p33tf[!mut_p33tf$AAChange %in% mut_p33tf$AAChange[duplicated(mut_p33tf$AAChange)], ]
outdir <- "/Users/shuo/Desktop/Project2_Discovering neoantigen specificity of tumor reactive T cells/GlioblastomaCollaboration/Data/Mutations/Pt33"
write.csv(mut_p33tf, paste0(outdir, "P33TF_mutations_duplicatedAAChange_removed.csv"))
table(mut_p33tf$sample)

mut_p33tr <- as.data.frame(rbind(mut_p33b, mut_p33tr))
sum(duplicated(mut_p33tr$AAChange))
mut_p33tr <- mut_p33tr[!mut_p33tr$AAChange %in% mut_p33tr$AAChange[duplicated(mut_p33tr$AAChange)], ]
outdir <- "/Users/shuo/Desktop/Project2_Discovering neoantigen specificity of tumor reactive T cells/GlioblastomaCollaboration/Data/Mutations/Pt33"
write.csv(mut_p33tr, paste0(outdir, "P33TR_mutations_duplicatedAAChange_removed.csv"))
table(mut_p33tr$sample)

```

